version: '3'

services:
  # Creamos nuestro primer servicio para la base de datos
  db:
    # El nombre del contenedor
    container_name: ${MONGO_DB_NAME}
    # Imagen de mongo
    image: mongo:6.0.6
    # Definimos un volumen
    volumes:
      - pokemon-db:/data/db
    # ports:
      # - 27017:27017
    # Indicamos que el contenedor se reinicie cuando se reinicia el contenedor
    restart: always
    # Indicamos las variables de entorno
    environment:
      # Obtenemos las variables de entorno del archivo .env entre ${}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    # Indicamos los comandos
    command: ['--auth']

  # Creamos el segundo servicio
  mongo-express:
    # Nombre del contenedor
    container_name: mongo-express
    # Depende de la base de datos
    depends_on:
      - db
    # Imagen de mongo express
    image: mongo-express:1.0.0-alpha.4
    # Indicamos las variables de entorno
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB_NAME}
    # Puerto de host:Puerto expuesto
    ports:
      - 8080:8081
    restart: always

  # Servicio de la aplicacion
  poke-app:
    # Depende de la base de datos y de mongo-express
    depends_on:
      - db
      - mongo-express
    # Imagen
    image: klerith/pokemon-nest-app:1.0.0
    # Variables de entorno
    environment:
      MONGODB: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_DB_NAME}:27017
      DB_NAME: ${MONGO_DB_NAME}
    restart: always

# Definicion de los volumenes utilizados
volumes:
  pokemon-db:
    # driver: local
    external: false
