apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # cesar@google.com in base64 = Y2VzYXJAZ29vZ2xlLmNvbQ==
  DB_USER_EMAIL: Y2VzYXJAZ29vZ2xlLmNvbQ==
  # M11ncr3d1bl3S3cr3tK3y in base64 = TTExbmNyM2QxYmwzUzNjcjN0SzN5
  DB_PASSWORD: TTExbmNyM2QxYmwzUzNjcjN0SzN5
