apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # postgres in base64 = cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  # M11ncr3d1bl3S3cr3tK3y in base64 = TTExbmNyM2QxYmwzUzNjcjN0SzN5
  DB_PASSWORD: TTExbmNyM2QxYmwzUzNjcjN0SzN5
